import Sidebar from '@/components/sidebar/Sidebar'
import './globals.css'
import { Work_Sans } from 'next/font/google'

const inter = Work_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        {/* <Sidebar /> */}
        {children}
        </body>
    </html>
  )
}
